### PR TITLE
MSVC 2015 support & move/cleanup VC2005 projects into VC2005 folder

### PR DESCRIPTION
**Pull request by n506**

### CODE REVIEW

**Comment by n506** [comment]
wait till tomorrow please, i'll add proper worker dir and config.cfg handling for tests

**Comment by n506** [comment]
ok, now its complete i think.

VS2015 tested, VS2005 should be ok, but i cant test

**Comment by n506** [comment]
oh no.. so.. fast.. ane more cleanup later

**Comment by n506** [comment]
ok, right now i see no warnings/errors about building process in any of the combinations -  release/debug/x64/x32

**Comment by zsummer** [comment]
thanks your contribution !

**Comment by n506** [comment]
sorry for long thread, last time i've extensively used c++ was in 2002 )

**Pull request merged**
