### PR TITLE
Windows console code page handling (ANSI->OEM)

### PR DESCRIPTION
**Pull request by n506**
Short problem description is - Windows use OEM codepage for console and ANSI codepage for other purposes

Here are longer description https://en.wikipedia.org/wiki/Windows_code_page

### CODE REVIEW

**Comment by zsummer** [comment]
I test this pull code.   I think log4z had this feature that in log4z.h :   
  
```   
    template<class _Elem,class _Traits,class _Alloc> //support std::string, std::wstring  
    inline Log4zStream & operator <<(const std::basic_string<_Elem, _Traits, _Alloc> & t){ return *this << t.c_str(); }  
   
    inline zsummer::log4z::Log4zStream & zsummer::log4z::Log4zStream::writeWString(const wchar_t* t);  
```   
  
  
it's can transfer wchar to oem codepage.    
support wchar, std::wstring.

**Comment by n506** [comment]
nope, its different things.

wchar & wstring does not offer codepage conversion, and works with ANSI coding, which is user thruout the windows except console output, which needs OEM codings, and this conversion makes my PR.

i've already added test code to fast_test and it works as it should with my patch and not as it should without.

if you interested, i can make screenshots to demonstrate the difference (i think you dont want to reinstall windows) )

**Comment by n506** [comment]
patch_vis
Here is demonstration

**Comment by zsummer** [comment]
thank you.  I had known what's this with your help. but I think.  this feature  to project have a slim chance of used ,  and so  I think,  I need time to  merge it.

**Comment by n506** [comment]
this feature is useful for any output using non english locale (with diacritics , cyrillic etc letters)

**Pull request merged**
